import Head from "next/head";
import Nav from "../components/navbar";
import Popup from "../components/popup";
import EmptyState from "../components/emptyState";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Popup ToggleButton={EmptyState} />
    </div>
  );
}
